/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yolo.gui;

import com.yolo.bll.StaffBLL;
import java.awt.Color;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author NGOCHUNG
 */
public class ForgotPassword_GUI extends javax.swing.JFrame {
    StaffBLL customerBLL = new StaffBLL();
    public JFrame Login_GUI;
    Color trans = new Color(0, 0, 0, 0);

    /**
     * Creates new form ForgotPassword_GUI
     */
    public ForgotPassword_GUI() {
        initComponents();
        
        jPanel1.setBackground(trans);
        setBackground(trans);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtUserNameOrEmail = new javax.swing.JTextField();
        btnLayLaiMatKhau = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 0));
        jLabel11.setText("Tài Khoản/Email:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 240, -1));
        jPanel1.add(txtUserNameOrEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 350, 29));

        btnLayLaiMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        btnLayLaiMatKhau.setForeground(new java.awt.Color(0, 153, 0));
        btnLayLaiMatKhau.setText("Lấy lại mật khẩu");
        btnLayLaiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayLaiMatKhauActionPerformed(evt);
            }
        });
        jPanel1.add(btnLayLaiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 130, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 0));
        jLabel10.setText("Quên Mật Khẩu");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 380, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/yolo/gui/iconset4/minimize.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 20, -1, -1));

        lbExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/yolo/gui/iconset4/exit.png"))); // NOI18N
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
        });
        jPanel1.add(lbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/yolo/gui/iconset4/forgotpassword_GUI.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleParent(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLayLaiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayLaiMatKhauActionPerformed
         try {
             // TODO add your handling code here:
             customerBLL.quenMatKhau(txtUserNameOrEmail.getText());
         } catch (UnsupportedEncodingException ex) {
             Logger.getLogger(ForgotPassword_GUI.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_btnLayLaiMatKhauActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setState(ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        // TODO add your handling code here:
        Login_GUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbExitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLayLaiMatKhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbExit;
    private javax.swing.JTextField txtUserNameOrEmail;
    // End of variables declaration//GEN-END:variables
}
